require 'fileutils'

SIREN = 'libsiren.dylib'

FRAMEWORKS = %w[
  CoreFoundation
  CoreServices
  CoreAudio
  AudioUnit
  AudioToolbox
]

LIBS = %w[
  /usr/local/lib/libportaudio.a
]

SRC = %w[
  siren.h
  siren.c
]

file SIREN => [*SRC] do |t|
  frameworks = FRAMEWORKS.map { |f| "-framework #{f}" } * " "
  libs = LIBS * " "
  sh "gcc -Wall -c -fPIC -O3 siren.c"
  sh "gcc -dynamiclib #{frameworks} #{libs} siren.o -o #{t.name}"
end

task :test => SIREN

task :clean do
  FileUtils.rm_f '*.o'
  FileUtils.rm_f '*.dylib'
end

task :default => [SIREN, :test]

